apiVersion: batch/v1
kind: CronJob
metadata:
  name: reset-geofences-checkins
  namespace: timetracker
spec:
  # every hour at 21:20
  schedule: "20 21 * * *"
  successfulJobsHistoryLimit: 2
  failedJobsHistoryLimit: 2
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: reset-geofences-checkins
              image: yauritux/busybox-curl
              imagePullPolicy: IfNotPresent
              command:
                - /bin/sh
                - -ec
                - curl -X PUT http://api-service:30000/api/schedule?jobclass=RESET_GEOFENCE_CHEKINS
          restartPolicy: Never
