apiVersion: batch/v1
kind: CronJob
metadata:
  name: dump-models
  namespace: timetracker
spec:
  # every day at 12:05
  schedule: "5 12 * * *"
  successfulJobsHistoryLimit: 2
  failedJobsHistoryLimit: 2
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: dump-models
              #image: busybox:stable
              image: yauritux/busybox-curl
              imagePullPolicy: IfNotPresent
              command:
                - /bin/sh
                - -ec
                - curl -X PUT http://api-service:30000/api/schedule?jobclass=DUMP_MODELS
          restartPolicy: Never
