---
# -----------------------------------------------------------
# Deployment/Pod
# -----------------------------------------------------------
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  namespace: timetracker
  labels:
    app: frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
      annotations:
        author: Gernot H. Reichel
    spec:
      containers:
        - name: frontend
          image: nobio/timetracker-ui:master.k8s
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 80
          readinessProbe:
            httpGet:
              scheme: HTTP
              path: /
              port: 80
            initialDelaySeconds: 10
            periodSeconds: 5
          livenessProbe:
            httpGet:
              scheme: HTTP
              path: /
              port: 80
            initialDelaySeconds: 10
            periodSeconds: 5
          resources:
            limits:
              memory: 512Mi
              cpu: "0.5"
            requests:
              memory: 256Mi
              cpu: "0.2"
---
# -----------------------------------------------------------
# Service
# -----------------------------------------------------------
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: timetracker
spec:
  type: LoadBalancer
  selector:
    app: api
  ports:
    - protocol: TCP
      port: 80
      targetPort: http
