---
# -----------------------------------------------------------
# Deployment/Pod
# -----------------------------------------------------------
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb-deployment
  namespace: timetracker
  labels:
    app: mongodb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
        - name: mongodb
          image: mongo:4.4
          args: ["--dbpath", "/data/db"]
          ports:
            - containerPort: 27017
          resources:
            limits:
              memory: 512Mi
              cpu: "0.5"
            requests:
              memory: 256Mi
              cpu: "0.2"
          livenessProbe:
            exec:
              command:
                - mongo
                - --disableImplicitSessions
                - --eval
                - "db.adminCommand('ping')"
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 6
          readinessProbe:
            exec:
              command:
                - mongo
                - --disableImplicitSessions
                - --eval
                - "db.adminCommand('ping')"
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 6
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mongodb-secret
                  key: mongodb-user
            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongodb-secret
                  key: mongodb-password
          volumeMounts:
            - name: mongodb-storage
              mountPath: "/data/db"
      volumes:
        - name: mongodb-storage
          persistentVolumeClaim:
            claimName: mongodb-data-claim
---
# -----------------------------------------------------------
# Service
# -----------------------------------------------------------
apiVersion: v1
kind: Service
metadata:
  name: mongodb-service
  namespace: timetracker
spec:
  type: NodePort
  selector:
    app: mongodb
    #app.kubernetes.io/name: mongodb
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
      nodePort: 30001
---
# -----------------------------------------------------------
# Volume
# -----------------------------------------------------------
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongodb-data
  namespace: timetracker
  labels:
    type: local
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 1Gi
  hostPath:
    path: /data/mongodb
---
# -----------------------------------------------------------
# Volume Claim
# -----------------------------------------------------------
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongodb-data-claim
  namespace: timetracker
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteOnce
  volumeName: mongodb-data
  resources:
    requests:
      storage: 1Gi
