GET http://localhost:30000/api/users

###

POST http://localhost:30000/api/users
Content-Type: application/json

{
    "name": "Tester",
    "password": "test12345"
}

###

POST http://localhost:30000/api/auth/login
Content-Type: application/json

{
    "name": "Tester",
    "password": "test12345"
}

###

POST http://localhost:30000/api/auth/token
Content-Type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiVGVzdGVyIiwiaWF0IjoxNTc5NDQ3NTc4LCJleHAiOjE1ODIwMzk1Nzh9.xJw5aYP-popOaFpP-vXLA0wgcIqROY8-W-uSKYKQ4Sk"
}

###

GET http://localhost:30000/api/ping
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiVGVzdGVyIiwiaWF0IjoxNTc5NDMxODE0LCJleHAiOjE1Nzk0MzI3MTR9.wKBD4wP5q8SkeRYYkVWLa5iP_jGrJaE1PUfmGpmoLK4

###

GET http://localhost:30000/api/ping
Authorization: Bearer xxx.yyy.zzz

###

POST http://localhost:30000/api/auth/logout
Content-Type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiVGVzdGVyIiwiaWF0IjoxNTc5MzY4NzQzLCJleHAiOjE1ODE5NjA3NDN9.JVPvv8faZDWzmkPzOQE7WdI-gZktl-ec7KIsfT3F1pY"
}