GET http://localhost:30000/api/users

###

POST http://localhost:30000/api/users
Content-Type: application/json

{
    "name": "Tester",
    "password": "test12345"
}

###

POST http://localhost:30000/api/users/login
Content-Type: application/json

{
    "name": "Tester",
    "password": "test12345"
}

###

GET http://localhost:30000/api/ping
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiVGVzdGVyIiwiaWF0IjoxNTc4OTAyNDIwLCJleHAiOjE1Nzg5MDMzMjB9.qG5WZWZk6xXn7awXI3YUL-RUIJJKVI0HmOQf9XNxc4I
###

GET http://localhost:30000/api/ping
Authorization: Bearer xxx.yyy.zzz