POST http://localhost:30000/api/auth/login
Content-Type: application/json

{
    "username": "nobio",
    "password": "schernoo"
}

###

GET http://localhost:30000/api/toggles
Authorization: : Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im5vYmlvIiwibmFtZSI6Ikdlcm5vdCBILiBSZWljaGVsIiwibWFpbEFkZHJlc3MiOiJnZXJub3RAZGllLXJlaWNoZWxzLmRlIiwiaWF0IjoxNjQwNzk4MzkyLCJleHAiOjE2NDA3OTg2OTJ9.wtP4usT6WVlyXmM5Dc7YbMgnh2i4rUk0rnKRP7DzjwI

###

POST  http://localhost:30000/api/toggles
Content-Type: application/json

{
    "name": "LOGIN",
    "toggle": "true",
    "notification": "Login"
}

###

POST  http://localhost:30000/api/toggles
Content-Type: application/json

{
    "name": "CREATE_USER",
    "toggle": "true",
    "notification": "Create new user"
}

###

POST  http://localhost:30000/api/toggles
Content-Type: application/json

{
    "name": "UPDATE_USER",
    "toggle": "true",
    "notification": "Update user"
}

###

POST  http://localhost:30000/api/toggles
Content-Type: application/json

{
    "name": "DELETE_USER",
    "toggle": "true",
    "notification": "Delete user"
}

###

DELETE http://localhost:30000/api/toggles/61cc9966f30fd42491b46ed2
Authorization: Bearer xxx.yyy.zzz

###
