GET http://localhost:30000/api/stats/1657490400000/week?accumulate=false&fill=false
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im5vYmlvIiwibmFtZSI6Ikdlcm5vdCBILiBSZWljaGVsIiwibWFpbEFkZHJlc3MiOiJnZXJub3RAZGllLXJlaWNoZWxzLmRlIiwiaWF0IjoxNjgyODQzNDc2LCJleHAiOjE2ODI4NDM0ODZ9.gVmKABMbSjUipqIbahZMicTH8aSnEmY8Y2qgF7JZ158

###
GET https://localhost:30443/api/stats/1684706400000/week?accumulate=false&fill=true
###

GET https://79.219.206.27/api/stats/1684706400000/week?accumulate=false&fill=true
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im5vYmlvIiwibmFtZSI6Ikdlcm5vdCBILiBSZWljaGVsIiwibWFpbEFkZHJlc3MiOiJnZXJub3RAZGllLXJlaWNoZWxzLmRlIiwiaWF0IjoxNjg4MTM5MzIxLCJleHAiOjE2ODgxNDAyMjF9.5p3_NsbIrxPTPqg8SfkIkNY93dy3uL04ZymV_Gt5LLg